# ArchBlock main configuration file.

# Database configuration.
db_config:
    # JDBC driver to use. Defaults to MySQL, "com.mysql.jdbc.Driver"
    jdbc_driver: "com.mysql.jdbc.Driver"

    # SQL dialect to use. Defaults to MySQL 5, "libs.org.hibernate.dialect.MySQL5InnoDBDialect"
    # Bundled Hibernate dialects should start with "libs.".
    hibernate_dialect: "libs.org.hibernate.dialect.MySQL5InnoDBDialect"

    # JDBC connection URL. You may change "localhost", "3306" and "archblock" as needed
    # to change the database host, port and name respectively.
    connection_url: "jdbc:mysql://localhost:3306/archblock"

    # Username to use for the database
    username: "archblock"

    # Login password for the above user. Can be empty.
    password: "SomeKindOfSecurePasswordButNotThisOne"

    # Debug mode. This will print all the generated SQL to the terminal (which could slow things down quite a bit)
    debug: false

# Worlds to disable this plugin for.
disabled_worlds:
- some_world_name  # For example.

# Don't edit this - you'll break your configuration.
version: "0.0.1"
