# ArchBlock main configuration file.

# Database configuration.
db_config:
    # JDBC driver to use. Defaults to MySQL, "com.mysql.jdbc.Driver"
    jdbc_driver: "com.mysql.jdbc.Driver"

    # SQL dialect to use. Defaults to MySQL, "org.hibernate.dialect.MySQLDialect"
    hibernate_dialect: "org.hibernate.dialect.MySQLDialect"

    # JDBC connection URL. You may change "localhost", "3306" and "archblock" as needed
    # to change the database host, port and name respectively.
    connection_url: "jdbc:mysql://localhost:3306/archblock"

    # Username to use for the database
    username: "archblock"

    # Login password for the above user. Can be empty.
    password: "SomeKindOfSecurePasswordButNotThisOne"

# Worlds to disable this plugin for.
disabled_worlds:
- some_world_name  # For example.

# Don't edit this - you'll break your configuration.
version: "0.0.1"
