name: ArchBlock
main: com.archivesmc.archblock.Plugin
version: 0.0.1
author: Gareth Coles
website: https://github.com/TheArchives/ArchBlock

depend: [WGCustomFlags, WorldEdit, WorldGuard]

commands:
    friend:
        description: Add another player as a friend, and allow them to edit your blocks
        usage: /<command> [player]
        aliases: [fr, f]
#    friends:
#        description: List everyone you've added as a friend
#        usage: /<command>
#        aliases: [fs]
    setowner:
        description: Set a player as the owner of a (WorldEdit) selecion of blocks
        usage: /setowner [player]
        aliases: [so]
    unfriend:
        description: Remove another player from your friends list, preventing them from editing your blocks
        usage: /<command> [player]
        aliases: [ufr, uf]

permissions:
    archblock.*:
        description: Gives access to all commands and overrides
        children:
            archblock.override: true
            archblock.admin: true
    archblock.bypass:
        description: Allows a player to bypass all block protection
        default: op
    archblock.admin:
        description: Gives a player access to all admin commands
        default: op
